/*!
 * Blocks by Pixel & Tonic
 *
 * @package   Blocks
 * @author    Pixel & Tonic, Inc.
 * @copyright Copyright (c) 2012, Pixel & Tonic, Inc.
 * @license   http://blockscms.com/license1.0.html Blocks License
 * @link      http://blockscms.com
 */
(function(a){Blocks.QuickPostWidget=Blocks.Base.extend({params:null,initBlocks:null,$widget:null,$form:null,$formClone:null,$spinner:null,$errorList:null,loading:false,init:function(b,d,c){this.params=d;this.initBlocks=c;this.$widget=a("#widget"+b);this.$form=this.$widget.find("form:first");this.$spinner=this.$form.find(".spinner");this.$formClone=this.$form.clone();this.initForm()},initForm:function(){this.addListener(this.$form,"submit","onSubmit");this.initBlocks()},onSubmit:function(b){b.preventDefault();if(this.loading){return}this.loading=true;this.$spinner.removeClass("hidden");var d=Blocks.getPostData(this.$form),c=a.extend({enabled:1},d,this.params);Blocks.postActionRequest("entries/saveEntry",c,a.proxy(function(e){if(this.$errorList){this.$errorList.children().remove()}if(e.success){Blocks.cp.displayNotice(Blocks.t("Entry saved."));var g=this.$formClone.clone();this.$form.replaceWith(g);this.$form=g;this.initForm();if(typeof Blocks.RecentEntriesWidget!="undefined"){for(var h=0;h<Blocks.RecentEntriesWidget.instances.length;h++){var k=Blocks.RecentEntriesWidget.instances[h];if(!k.params.sectionId||k.params.sectionId==this.params.sectionId){k.addEntry({url:e.cpEditUrl,title:e.entry.title,postDate:e.entry.postDate.date.substr(0,10),username:e.author.username})}}}}else{Blocks.cp.displayError(Blocks.t("Couldn’t save entry."));if(e.errors){if(!this.$errorList){this.$errorList=a('<ul class="errors"/>').insertAfter(this.$form)}for(var j in e.errors){for(var h=0;h<e.errors[j].length;h++){var f=e.errors[j][h];a("<li>"+f+"</li>").appendTo(this.$errorList)}}}}this.loading=false;this.$spinner.addClass("hidden")},this))}})})(jQuery);